### ISSUE TITLE
stackage-setup basic outline (and for discussion)

### ISSUE THREAD

**Issue by chrisdone** [fpco/stackage-cli#17]
We would like there to be a setup command for stackage. This will be
part of the base setup of stackage-cli, as a bootstrapping
process. Let's call it `stackage-setup` for now and consider what we
want for users:

1. A user has no pre-existing install.
2. The target user is Windows, Linux and OS X users.
3. We'd like everyone to be able to run the tool to automatically
   download and unpack:
   1. GHC
   2. Cabal-install (for now)
   3. Any other tools considered necessary for a standard Haskell
      setup.
   4. Automatically setup the ~/.cabal/config with constraints limited
      to the latest LTS Haskell release.

This means there'll be a binary that we'll distribute for each
operating system.

Operating systems:

* On Windows, we'd like to re-use the existing work done on MinGHC.
* For Linux, we'd like to download regular GHC binaries and unpack to a
  predictable location like `/opt/ghc/ver/`.
* For OS X, I'm not sure yet. There is the GHC for Mac OSX, which
  somewhat mirrors the purpose of MinGHC.

In all cases, it's not clear whether to update the PATH, or whether to
have `stackage` tools automatically configure the PATH, similar to how
nix and cabal sandbox do, then we might allow e.g. `stackage shell` to
bring us into the shell. (When using dockers, this could instead drop
you into the docker container.)

I will make separate issues for each operating system.

I'll make a separate outline issue regarding verifying signatures of
these downloads, which we may in part or in whole host on our servers
along with .asc signatures, or otherwise leave on their respective
hosts and keep signatures separate.

**Comment by DanBurton** [comment]
As discussed elsewhere, the upcoming iteration of "auto-update" will be in the form of `stackage-setup` installing `stackage-cli` just like it installs `ghc` and friends. (See #26)

As for PATH and config discussion, #20, #21, #22, and #23 address these.

Further improvements will be proposed in #37 and future issues.
