### ISSUE TITLE
Support getConfigMaybe and getConfig

### ISSUE THREAD

**Issue by chrisdone** [fpco/stackage-cli#21]
As part of the `Stackage.CLI` library which plugins can use, and the latter will auto-create a config.

**Comment by chrisdone** [comment]
Implement for `Stackage.Config` as in https://github.com/fpco/stackage-common/issues/1.

**Comment by DanBurton** [comment]
Since the config can draw settings from multiple sources, I don't think `getConfigMaybe` makes sense anymore. There is only `getConfig`, which will settle for defaults and will not auto-create a config file. We can have separate functionality for creating these config files.
