### ISSUE TITLE
stackage PATH

### ISSUE THREAD

**Issue by chrisdone** [fpco/stackage-cli#23]
Make a `getConfig` function in the `Stackage.CLI` library which will

* Get the config.
* Apply the appropriate PATH settings for this snapshot.

**Comment by DanBurton** [comment]
Note: put this in stackage-common.

**Comment by chrisdone** [comment]
Implement for `Stackage.Environment` as in https://github.com/fpco/stackage-common/issues/1.

**Comment by DanBurton** [comment]
This is partially implemented. What remains is to correctly interpret "path settings for this snapshot".

**Comment by DanBurton** [comment]
Since this work is being done in stackage-common, "what remains" for this issue will be tracked under fpco/stackage-common#3
