### ISSUE TITLE
Stackage bundles determined storage and storage format

### ISSUE THREAD

**Issue by chrisdone** [fpco/stackage-cli#24]
This issue is about where we'll store our GHC and Cabal should be stored. Things to determine:

* Where do we host? Probably S3. We're already hosting MinGHC on S3.
* Do we rely on third-party sources or repackage ourselves?
* Determine some kind of release cycle.

Pinging @snoyberg @manny-fp. Related stackage-server issues https://github.com/fpco/stackage-server/issues/87 and https://github.com/fpco/stackage-server/issues/88

**Comment by DanBurton** [comment]
I've put the tarballs up on s3, and updated stackage-content to use those urls.

See: https://github.com/fpco/stackage-content/commit/46d2b3a635c8e66cfed27c20092869abdc0b94ac
