### ISSUE TITLE
stackage-exec

### ISSUE THREAD

**Issue by DanBurton** [fpco/stackage-cli#25]
Do the needful.

**Comment by chrisdone** [comment]
Implement for `Stackage.Environment` as in https://github.com/fpco/stackage-common/issues/1.

**Comment by DanBurton** [comment]
Note: put in stackage-common

**Comment by DanBurton** [comment]
For now, the only workflow supported is the "do things yourself with cabal" workflow. stackage-exec will put the right `ghc` and `cabal` on your PATH, and leave it up to you to take it from there.

Let's create new issues for other workflows that we want to support. (e.g. the "run in docker" workflow.)

Detecting the correct versions of things based on a given snapshot is also not done yet. Progress on that is tracked in #23.
