### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by tfausak** [fpco/stackage-cli#28]
I tried to install version 0.0.0 on OS X 10.10.3 with GHC 7.8.3 and Cabal 1.22.2.0. It complains that `endOfLine` is not in scope. 

``` sh
$ uname -a
Darwin mbafo.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3
$ cabal --version
cabal-install version 1.22.2.0
using version 1.22.2.0 of the Cabal library 
$ date
Mon Apr 20 08:03:43 CDT 2015
$ cabal update
Downloading the latest package list from hackage.haskell.org
Skipping download: Local and remote files match.

$ cabal install stackage-cli-0.0.0
...
[2 of 2] Compiling Main             ( main/Purge.hs, dist/build/stackage-purge/stackage-purge-tmp/Main.o )

main/Purge.hs:101:23: Not in scope: ‘endOfLine’

main/Purge.hs:107:67: Not in scope: ‘endOfLine’
cabal: Error: some packages failed to install:
stackage-cli-0.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

Here is the offending line: <https://github.com/fpco/stackage-cli/blob/0.0.0/main/Purge.hs#L107>. The `endOfLine` parser comes from [Text.Parsec.Char](http://hackage.haskell.org/package/parsec-3.1.9/docs/Text-Parsec-Char.html#v:endOfLine). I don't think it's available in parsec 3.1.5, which Cabal decided to use.

**Comment by snoyberg** [comment]
Thanks for the report. @DanBurton Can you look into this?

**Comment by DanBurton** [comment]
Yep. Looks like we need a lower bound constraint on Parsec, or I can rewrite that particular parser.

**Comment by snoyberg** [comment]
The function's pretty short:

```haskell
endOfLine :: (Stream s m Char) => ParsecT s u m Char
endOfLine           = newline <|> crlf       <?> "new-line"
```

How about conditionally including it?

**Comment by DanBurton** [comment]
This should now be resolved with 0.0.0.2 on Hackage, can you confirm?

**Comment by tfausak** [comment]
Unfortunately it still fails.

``` sh
$ cabal install stackage-cli-0.0.0.2
...
[2 of 2] Compiling Main             ( main/Purge.hs, dist/build/stackage-purge/stackage-purge-tmp/Main.o )

main/Purge.hs:104:25: Not in scope: ‘crlf’
cabal: Error: some packages failed to install:
stackage-cli-0.0.0.2 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by DanBurton** [comment]
Whoops, sorry about that.

I tested on my machine this time:

```
$ git clone git@github.com:fpco/stackage-cli
$ cd stackage-cli
$ cabal sandbox init # you can skip this part
$ cabal install --constrait 'parsec<3.1.6'
```

@snoyberg can you double check?

**Comment by snoyberg** [comment]
Looks good to me, just compiled with parsec-3.1.5. Please go ahead and release.

**Comment by DanBurton** [comment]
Uploaded 0.0.0.3 to hackage. @tfausak it should at least make it past these parsec errors now. Can you confirm?

**Comment by tfausak** [comment]
:+1: That did the trick. Thank you for the fast fix!
