### ISSUE TITLE
Set up a Travis job to check multiple GHC versions

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-cli#30]
This would hopefully prevent things like #29

**Comment by snoyberg** [comment]
More relevant information at: https://github.com/hvr/multi-ghc-travis

**Comment by DanBurton** [comment]
A Travis job to just compile it? Do we want to start building a test suite as well?

**Comment by snoyberg** [comment]
A test suite would be a good addition, yes (I'll never say "no, don't add tests" ;) ). For now, it would just be to compile.

**Comment by drwebb** [comment]
Here it makes sense to me to build the project using a stackage cabal config (a strange bootstrapping in the context of the project). When 7.10 support for stackage hits it would be nice to have this script select the proper version to download.

**Comment by snoyberg** [comment]
Actually, I'd recommend going the opposite route. The goal of the Travis job is to catch errors as early as possible. Using a Stackage config will limit us to known good combinations, which will minimize the chance of discovering a failure.

**Comment by drwebb** [comment]
Alright, I did not think about it that way. It does make perfect sense as this is the getting started with Stackage tool and many new users will probably be compiling it based off of whatever is on Hackage.
