### ISSUE TITLE
Propose immediate improvements to stackage-setup for linux

### ISSUE THREAD

**Issue by DanBurton** [fpco/stackage-cli#37]
I (@DanBurton) will propose and create issues for various improvements to stackage-setup on linux, especially stackgage-setup.

**Comment by DanBurton** [comment]
* #24: host the tarballs in our own s3
* #26: also download happy, alex, and stackage-cli
* #38: detect missing system dependencies
* #43: clean up correctly after failed installation attempt
* #44: reduce system dependencies if possible & wise
* #45: improve error messages

**Comment by chrisdone** [comment]
Sounds good.

**Comment by snoyberg** [comment]
Looks good to me too. For #43, I have some thoughts on implementation, which essentially would be to make it work the way Shake does. For example, when downloading GHC, you'd check if the destination file is present. If not, download by saving to `destfile.tmp` and, when complete, renaming to `destfile`. Then if things fail later, it will never try to redo the download.

**Comment by DanBurton** [comment]
#44 and #45 are still being worked on. Also opened as a stackage-setup improvement:

#48 attempt to resume progress of failed installs

Now that these proposed issues have gotten the thumbs up, I'll go ahead and close this issue and continue working on the above mentioned issues.
