### ISSUE TITLE
stackage-setup should detect missing system dependencies

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-cli#38]
One dependency we likely can't do anything about is libgmp10, though we *should* add a comment to the download page about it. Beyond that, I just noticed when running via Docker that there's a dependency of `xz`:

```
# ./stackage-setup
setup for snapshot: lts-2.5
Selecting ghc-7.8
downloading: ghc-7.8.4-x86_64-unknown-linux-deb7.tar.xz
Verified sha1: 11aec12d4bb27f6fa59dcc8535a7a3b3be8cb787
Decompressing XZ archive
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
stackage-setup: callProcess: tar "xJf" "ghc-7.8.4-x86_64-unknown-linux-deb7.tar.xz" (exit 2): failed
```

It would be better if `stackage-setup` started by checking for presence of all necessary executables. I'll continue adding error messages I see when installing via Docker.

**Comment by snoyberg** [comment]
Requires build-essential:

```
configure: error: cannot find gcc nor clang in your PATH
stackage-setup: callProcess: ./configure "--prefix=/root/.stackage/environment/ghc/ghc-7.8.4" (exit 1): failed
```

**Comment by snoyberg** [comment]
After installing build-essential, stackage-setup then seems to be confused about the status of the GHC installation:

```
# ./stackage-setup
setup for snapshot: lts-2.5
Selecting ghc-7.8
Already have: ghc-7.8.4
downloading: cabal-install-1.20.0.3.tar.gz
Verified sha1: 444448b0f704420e329e8fc1989b6743c1c8546d
Decompressing GZ archive
./bootstrap.sh: 20: ./bootstrap.sh: ghc: not found
```

**Comment by DanBurton** [comment]
Something to improve: if the download of ghc fails, but gets far enough to create the `$STACKAGE_ROOT/environment/ghc/ghc-7.8.4/` folder, then it assumes that you already have ghc-7.8.4.

For now, you can just delete the folder so that it knows to try and install it. In the future, we'll want a better story for cleaning up failed install attempts.

**Comment by DanBurton** [comment]
On a related note, stackage-setup should add each item it installs to the PATH temporarily, so that it is available for use by the config scripts for items to follow. The yaml describing these items puts them in an ordered list for this reason.

**Comment by DanBurton** [comment]
Added simple dependency checking. This version is now uploaded to s3. @snoyberg verify?

**Comment by snoyberg** [comment]
Yes, this is working much better now.
