### ISSUE TITLE
MinGHC - failure with data-default-instances-old-locale

### ISSUE THREAD

**Issue by tomberek** [fpco/stackage-cli#39]
Vanilla install with MinGHC 7.10.1 on Windows 7
using `cabal install stackage-cli`
```
cabal: Error: some packages failed to install:
cookie-0.4.1.4 depends on data-default-instances-old-locale-0.0.1 which failed
to install.
data-default-0.5.3 depends on data-default-instances-old-locale-0.0.1 which
failed to install.
data-default-instances-containers-0.0.1 failed during the building phase. The
exception was:
ExitFailure 1
data-default-instances-old-locale-0.0.1 failed during the building phase. The
exception was:
ExitFailure 1
http-client-0.4.11.1 depends on data-default-instances-old-locale-0.0.1 which
failed to install.
http-client-tls-0.2.2 depends on data-default-instances-old-locale-0.0.1 which
failed to install.
publicsuffixlist-0.1 depends on data-default-instances-old-locale-0.0.1 which
failed to install.
stackage-cli-0.0.0.4 depends on data-default-instances-old-locale-0.0.1 which
failed to install.
```

contents of log for data-default-instances-old-locale
```
Building data-default-instances-old-locale-0.0.1...
Preprocessing library data-default-instances-old-locale-0.0.1...
[1 of 1] Compiling Data.Default.Instances.OldLocale ( Data\Default\Instances\OldLocale.hs, dist\build\Data\Default\Instances\OldLocale.o )
C:\Program Files\MinGHC-7.10.1\ghc-7.10.1\mingw\bin\ar.exe: dist\build\libHSdata-default-instances-old-locale-0.0.1-6jcjjaR25tK4x3nJhHHjFM.a-12252\libHSdata-default-instances-old-locale-0.0.1-6jcjjaR25tK4x3nJhHHjFM.a: No such file or directory
```
more:
```
Building data-default-instances-containers-0.0.1...
Preprocessing library data-default-instances-containers-0.0.1...
[1 of 1] Compiling Data.Default.Instances.Containers ( Data\Default\Instances\Containers.hs, dist\build\Data\Default\Instances\Containers.o )
C:\Program Files\MinGHC-7.10.1\ghc-7.10.1\mingw\bin\ar.exe: dist\build\libHSdata-default-instances-containers-0.0.1-GVMvZTIbSoDCiC0TxHw1BG.a-10648\libHSdata-default-instances-containers-0.0.1-GVMvZTIbSoDCiC0TxHw1BG.a: No such file or directory
```
(ar.exe exists)

**Comment by snoyberg** [comment]
I think I've read that this is a known bug with GHC 7.10.1 on Windows. I'd recommend sticking to 7.8.4 for the time being (not to mention, it's the version supported by Stackage and LTS Haskell).

**Comment by tomberek** [comment]
You're right: https://github.com/haskell/cabal/issues/2502

**Comment by snoyberg** [comment]
Thanks for the link. In that case, I'd like to close this issue, as there's nothing in stackage-cli or MinGHC we can do to fix it, it has to be resolved upstream.

**Comment by tomberek** [comment]
For anyone else searching for this:
https://github.com/haskell/cabal/issues/2525 outlines a procedure that works.
Basically, perform `cabal get` on data-default-instances-old-locale and data-default-instances-containers, `cd` into each folder, perform `cabal install` and then try again with `cabal install stackage-cli`

**Comment by DanBurton** [comment]
What we might want to do here is have stackage-cli spit out warnings or
errors if `ghc --version` doesn't match the selected snapshot's intended
ghc version.

stackage-cli is currently intended for ghc-7.8 only (simply because there
are no ghc-7.10 snapshots available on Stackage yet) and I don't think that
has been communicated clearly.

-- Dan Burton

**Comment by DanBurton** [comment]
On second look, what I'm talking about in my last comment actually appears to be unrelated to this issue, but I've opened a new issue about it nonetheless. #40
