### ISSUE TITLE
stackage-init target

### ISSUE THREAD

**Issue by chrisdone** [fpco/stackage-cli#4]
The `executable` target should be `stackage-init`. This is one of the built-in plugins that come with the project and serves as a good demonstration.

Setup a `cabal.config` file in the current directory by either receiving a snapshot hash or alias as argument, or by prompting the user to enter one. It may default to `lts` with a "RET to choose default". Or optionally be like `Enter snapshot (tls/nightly/<hash>):`, so that one can just grab whatever lts or nightly is current. Maybe also support --lts or --nightly flag. There's a bit of freedom here, but think: convenient. Think of users first coming to hackage and also experts.

**Comment by 3noch** [comment]
@chrisdone Did your suggestion ever make it in? I was just struggling with that today: "What are valid snapshots?" Would be awesome to list them out somehow.
