### ISSUE TITLE
Open sourcing

### ISSUE THREAD

**Issue by chrisdone** [fpco/stackage-cli#8]
Some items for clean up before open sourcing:

* [x] Fix the docs for commandline options (e.g.'stuff' and 'junk' with something proper) and any other "TODO"-ish code.
* [x] Add FP Complete copyright field to .cabal file.
* [x] Check that `cabal haddock` yields something reasonably nice as an FP Complete product.
* [x] Write up a `README` explaining what the tool is for, the basic architecture and the few included commands.
* [x] I think our dependency on `base` is too restrictive. Can it be lifted to <5?
* [x] A final review by other FP Complete devs to try it out.

That should be it and then we can open source the project and upload to Hackage and include in Stackage.

**Comment by snoyberg** [comment]
Let's hold off on updating instructions on stackage.org/install and yesodweb.com/page/quickstart until we get more user feedback on the tool.
